### ISSUE TITLE
Doesn't recognize Footnotes

### ISSUE THREAD

**Issue by HughP** [pmendelski/google-addon-doc2md#1]
Within GoogleDocs it is possible to use Footnotes.  Google Footnotes are recognized as errors. However, in the flavor of Markdown I use (for Hugo) we use this syntax: https://www.markdownguide.org/extended-syntax/#footnotes, but even faking footnotes would likely be a good option: https://stackoverflow.com/questions/25579868/how-to-add-footnotes-to-github-flavoured-markdown

**Comment by pmendelski** [comment]
Hi, sorry for taking so long to add it.
I chose the extended format.
![Screenshot from 2020-10-05 08-13-15](https://user-images.githubusercontent.com/719718/95045810-1683a080-06e3-11eb-8434-1223ab76fd03.png)
