### ISSUE TITLE
Use image alt-text from Google docs

### ISSUE THREAD

**Issue by kaitlinnewson** [pmendelski/google-addon-doc2md#3]
When images have been added in the Google doc, the alt-text that has been added to that image is not carried over into the markdown. In markdown, alt-text is embedded for an image as `![Alt text](/path/to/img.jpg)`

**Comment by pmendelski** [comment]
Thanks for reporting the issue.
It's fixed it.

![Screenshot from 2020-10-05 08-15-56](https://user-images.githubusercontent.com/719718/95045896-47fc6c00-06e3-11eb-8fc0-74c7659aafb6.png)
